### ISSUE TITLE
Python Segmentation Fault

### ISSUE THREAD

**Issue by mmwaveguy** [Optware/Optware-ng#49] opened 2016-01-24 15:44 UTC
Linux axentraserver.akasha.mystora.com 2.6.22.18-Netgear #16 Sun Jun 13 19:54:46 EDT 2010 armv5tejl armv5tejl armv5tejl GNU/Linux

python27 crashes with segmentation fault

**Comment by mmwaveguy** [comment] 2016-01-24 20:21
Well I solved segmentation error by linking /lib/libc.so.6 to /opt/lib/libc.so.1 but now python complains about unresolved symbols.

do I also need a compliant version of libgcc?

**Comment by alllexx88** [comment] 2016-01-25 14:07
Optware-ng doesn't use `/lib/libc.so.6` or anything outside `/opt`:

```
[root@unknown /opt]$ ldd /opt/bin/python2.7
        libgcc_s.so.1 => /opt/lib/libgcc_s.so.1 (0x4012e000)
        libbz2.so.1.0 => /opt/lib/libbz2.so.1.0 (0x40084000)
        libcrypt.so.1 => /opt/lib/libcrypt.so.1 (0x400d4000)
        libdb-5.3.so => /opt/lib/libdb-5.3.so (0x4015c000)
        libncurses.so.5 => /opt/lib/libncurses.so.5 (0x402e4000)
        libreadline.so.6 => /opt/lib/libreadline.so.6 (0x40331000)
        libssl.so.1.0.0 => /opt/lib/libssl.so.1.0.0 (0x40375000)
        libz.so.1 => /opt/lib/libz.so.1 (0x400f9000)
        libffi.so.6 => /opt/lib/libffi.so.6 (0x403df000)
        libpython2.7.so.1.0 => /opt/lib/libpython2.7.so.1.0 (0x403f4000)
        libpthread.so.1 => /opt/lib/libpthread.so.1 (0x4056a000)
        libdl.so.1 => /opt/lib/libdl.so.1 (0x40591000)
        libutil.so.1 => /opt/lib/libutil.so.1 (0x405a5000)
        libm.so.1 => /opt/lib/libm.so.1 (0x405b6000)
        libc.so.1 => /opt/lib/libc.so.1 (0x405d7000)
        ld-uClibc.so.1 => /opt/lib/ld-uClibc.so.1 (0x400bd000)
        libcrypto.so.1.0.0 => /opt/lib/libcrypto.so.1.0.0 (0x40684000)
```

Do you happen to have `LD_PRELOAD` env variable set? I don't see other ways to have python2.7 load anything outside `/opt`.

armv5 `python27` works OK on my armv7 test machine, btw:

```
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by mmwaveguy** [comment] 2016-01-25 23:07
Problem Solved! 

I completely uninstalled all packages and re-installed python.  This worked.  Must have been some conflicting libraries or something from the old package installs.

**Comment by mmwaveguy** [comment] 2016-01-26 01:15
Well after all that the dreaded segmentation fault returns!  Running SABnzbd fails with a segmentation fault.

**Comment by mmwaveguy** [comment] 2016-01-26 02:53
Completely uninstalling all packages and deleting all files in /opt then reinstalling ipkg allowed me to run SABnzbd.  However SickRage now fails with a segmentation fault.

**Comment by alllexx88** [comment] 2016-03-17 18:40
@mmwaveguy I believe that, just like with #44, this issue is caused by kernel that is older than the headers from buildroot-armv5eabi-ng toolchain. Please try buildroot-armv5eabi-ng-legacy feed that was recently added, if you're still interested in this.

**Comment by alllexx88** [comment] 2016-04-11 05:42
Closing, since I assume this should work now with the `buildroot-armv5eabi-ng-legacy` feed

**Closed by alllexx88** 2016-04-11 05:42 UTC
