### ISSUE TITLE
vnstat missing libm.so.1

### ISSUE THREAD

**Issue by elRadix** [Optware/Optware-ng#54] opened 2016-02-01 19:58 UTC
Hi

I have issues running vnstat, installed the latest optware.ng for R7000 running XWRT

```
admin@router:/# ipkg install vnstat
Installing vnstat (1.10-2) to /opt/...
Downloading http://optware-ng.zyxmon.org/buildroot-armeabi-ng/vnstat_1.10-2_arm.ipk
Configuring vnstat
Successfully terminated.
admin@router:/# vnstat
vnstat: can't load library 'libm.so.1'
admin@router:/# 
```

**Comment by alllexx88** [comment] 2016-02-07 14:53
Hi,

I believe the issue is fixed now

**Closed by alllexx88** 2016-02-07 14:53 UTC

**Comment by elRadix** [comment] 2016-02-07 17:44
confirmed, its fixed

thank you!
