### ISSUE TITLE
git on ppc crashes

### ISSUE THREAD

**Issue by megazone23** [Optware/Optware-ng#56] opened 2016-02-03 01:54 UTC
When running the following command on big-endian hardware such as ppc:

 git pull -f origin master

The following error occurs:

 * branch            master     -> FETCH_HEAD
Updating f67f6e9..3f0efd1
Fast-forward
git: xdiff/xutils.c:358: xdl_hash_record: Assertion `*ptr == '\n'' failed.
error: merge died of signal 6, treat as error for now [f67f6e9]

Based on google searches on the error it has to do with the inclusion of XDL_FAST_HASH, it does not work on big-endian machines.

**Comment by alllexx88** [comment] 2016-02-07 13:41
I believe the issue is fixed now, thanks for reporting.

**Closed by alllexx88** 2016-02-07 13:41 UTC

**Comment by megazone23** [comment] 2016-02-07 19:44
Confirmed that the problem is fixed.  Thanks!
